base:
  main:
    image: greptime/greptimedb:integration-paas-test # Only for testing, will be changed by release of GreptimeDB.
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi

frontend:
  replicas: 1

meta:
  replicas: 1

datanode:
  replicas: 1
  storage:
    storageClassName: standard
    storageSize: 10Gi
    storageRetainPolicy: Retain
