image:
  registry: docker.io
  # The image repository
  repository: greptime/greptimedb
  # The image tag
  tag: 0.1.0-alpha-20221124-nightly

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

frontend:
  replicas: 1

meta:
  replicas: 1

datanode:
  replicas: 3
  storage:
    storageClassName: standard
    storageSize: 10Gi
    storageRetainPolicy: Retain

initializer:
  repository: greptime/greptimedb-initializer
  tag: latest

etcdEndpoints: ""

httpServicePort: 4000
grpcServicePort: 4001
mysqlServicePort: 4002
postgresServicePort: 4003
openTSDBServicePort: 4242

enablePrometheusMonitor: false
