image:
  registry: docker.io
  # The image repository
  repository: greptime/greptimedb
  # The image tag
  tag: 0.1.0-alpha-20230220-weekly
  # The image pull secrets.
  pullSecrets: []

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

frontend:
  replicas: 1
  service: {}
  componentSpec: {}

  tls: {}
    # secretName:
    # certificateMountPath:

meta:
  replicas: 1

datanode:
  replicas: 3
  storage:
    storageClassName: standard
    storageSize: 10Gi
    storageRetainPolicy: Retain

initializer:
  registry: docker.io
  repository: greptime/greptimedb-initializer
  tag: 0.1.0-alpha.9

# The etcdEndpoints need be modified to the actual etcd cluster.
etcdEndpoints: "etcd.default.svc.cluster.local:2379"

httpServicePort: 4000
grpcServicePort: 4001
mysqlServicePort: 4002
postgresServicePort: 4003
openTSDBServicePort: 4242

enablePrometheusMonitor: false

storage: {}
  # s3:
  #  bucket: ""
  #  region: ""
  #  secretName: ""
  #  prefix: ""
