apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  volumeClaimTemplates:
  - metadata:
      name: etcd-storage
    spec:
      storageClassName: {{ .Values.storage.storageClassName }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.volumeSize }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: etcd
        image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
        command:
          - "etcd"
          - "--name"
          - "$(HOSTNAME)"
          - "--data-dir"
          - "{{ .Values.storage.dataDir }}"
          - "--initial-advertise-peer-urls"
          - "http://$(HOSTNAME):{{ .Values.servicePorts.peer }}"
          - "--listen-peer-urls"
          - "http://0.0.0.0:{{ .Values.servicePorts.peer }}"
          - "--advertise-client-urls"
          - "http://$(HOSTNAME):{{ .Values.servicePorts.client }}"
          - "--listen-client-urls"
          - "http://0.0.0.0:{{ .Values.servicePorts.client }}"
          - "--initial-cluster"
          - "{{ .Release.Name }}-0=http://{{ .Release.Name }}-0.{{ .Release.Name }}:{{ .Values.servicePorts.peer }},{{ .Release.Name }}-1=http://{{ .Release.Name }}-1.{{ .Release.Name }}:{{ .Values.servicePorts.peer }},{{ .Release.Name }}-2=http://{{ .Release.Name }}-2.{{ .Release.Name }}:{{ .Values.servicePorts.peer }}"
          - "--initial-cluster-state"
          - "new"
          - "--initial-cluster-token"
          - "{{ .Release.Name }}"
        volumeMounts:
          - name: etcd-storage
            mountPath: ma{{ .Values.storage.dataDir }}
        ports:
          - name: client
            containerPort: {{ .Values.servicePorts.client }}
          - name: peer
            containerPort: {{ .Values.servicePorts.peer }}
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ETCDCTL_API
            value: "3"
