apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag }}
          command: ["/bin/sh", "-c"]
          args: ["/scripts/testing.sh"]
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if .Values.case.s3.enabled }}
            - name: S3_BUCKET
              value: {{ .Values.case.s3.bucket }}
            - name: AWS_REGION
              value: {{ .Values.case.s3.region }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.case.s3.accessKeyID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.case.s3.secretAccessKey }}
            {{- end }}
            {{- if .Values.case.kafka.enabled }}
            - name: KAFKA_ENDPOINT
              value: {{ .Values.case.kafka.endpoint }}
            {{- end }}
            {{- if .Values.case.rds.enabled }}
            - name: RDS_HOST
              value: {{ .Values.case.rds.host }}
            - name: RDS_PORT
              value: {{ .Values.case.rds.port | quote }}
            - name: RDS_DATABASE
              value: {{ .Values.case.rds.database }}
            - name: RDS_USERNAME
              value: {{ .Values.case.rds.username }}
            - name: RDS_PASSWORD
              value: {{ .Values.case.rds.password }}
            {{- end }}
          volumeMounts:
            - name: script
              mountPath: /scripts
            {{- if .Values.case.disk.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: {{ .Release.Name }}-scripts
            defaultMode: 0755
        {{- if .Values.case.disk.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
        {{- end }}
  backoffLimit: 0
