apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  base:
    main:
      image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
      resources:
{{ toYaml .Values.resources | indent 8 }}
  frontend:
    replicas: {{ .Values.frontend.replicas }}
  meta:
    replicas: {{ .Values.meta.replicas }}
    etcdEndpoints:
      - "{{ .Release.Name }}-etcd-svc.{{ .Release.Namespace }}:2379"
  datanode:
    replicas: {{ .Values.datanode.replicas }}
    storage:
      storageClassName: {{ .Values.datanode.storage.storageClassName }}
      storageSize: {{ .Values.datanode.storage.storageSize }}
      storageRetainPolicy: {{ .Values.datanode.storage.storageRetainPolicy }}
  enablePrometheusMonitor: {{ .Values.enablePrometheusMonitor }}
  httpServicePort: {{ .Values.httpServicePort }}
  grpcServicePort: {{ .Values.grpcServicePort }}
  mysqlServicePort: {{ .Values.mysqlServicePort }}
  postgresServicePort: {{ .Values.postgresServicePort }}
  openTSDBServicePort: {{ .Values.openTSDBServicePort }}
  initializer:
    image: '{{ .Values.initializerImage.registry }}/{{ .Values.initializerImage.repository }}:{{ .Values.initializerImage.tag }}'
