apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  base:
    main:
      {{- if .Values.base.main.image }}
      image: {{ .Values.base.main.image }}
      {{- end }}
      resources:
        requests:
          memory: {{ .Values.base.main.resources.requests.memory }}
          cpu: {{ .Values.base.main.resources.requests.cpu }}
        limits:
          memory:  {{ .Values.base.main.resources.limits.memory }}
          cpu: {{ .Values.base.main.resources.limits.cpu }}
  frontend:
    replicas: {{ .Values.frontend.replicas }}
  meta:
    replicas: {{ .Values.meta.replicas }}
    etcdEndpoints:
      - "{{ .Release.Name }}-etcd-svc.{{ .Release.Namespace }}:{{ .Values.etcd.servicePorts.client }}"
  datanode:
    replicas: {{ .Values.datanode.replicas }}
    storage:
      storageClassName: {{ .Values.datanode.storage.storageClassName }}
      storageSize: {{ .Values.datanode.storage.storageSize }}
      storageRetainPolicy: {{ .Values.datanode.storage.storageRetainPolicy }}
  enablePrometheusMonitor: false
