{{- if .Values.admissionWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "greptimedb-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "greptimedb-operator.name" . }}
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: {{ .Values.admissionWebhook.port }}
{{- end }}
