{{- if .Values.configToml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greptimedb-standalone.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-standalone.labels" . | nindent 4 }}
data:
  config.toml: |
{{ .Values.configToml | indent 4 }}
{{ include "greptimedb-standalone.objectStorageConfig" . | indent 4 }}
{{- end -}}
