apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "greptimedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - interval: 30s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "greptimedb.selectorLabels" . | nindent 6 }}
