{{- if .Values.objectStorage }}
{{- if .Values.objectStorage.credentials }}
{{- if not .Values.objectStorage.credentials.existingSecretName }}
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
stringData:
  {{- if .Values.objectStorage.s3}}
  GREPTIMEDB_STANDALONE__STORAGE__ACCESS_KEY_ID: {{ .Values.objectStorage.credentials.accessKeyId }}
  GREPTIMEDB_STANDALONE__STORAGE__SECRET_ACCESS_KEY: {{ .Values.objectStorage.credentials.secretAccessKey }}
  {{ else if .Values.objectStorage.oss }}
  GREPTIMEDB_STANDALONE__STORAGE__ACCESS_KEY_ID: {{ .Values.objectStorage.credentials.accessKeyId }}
  GREPTIMEDB_STANDALONE__STORAGE__ACCESS_KEY_SECRET: {{ .Values.objectStorage.credentials.secretAccessKey }}
  {{ else if .Values.objectStorage.gcs }}
  GREPTIMEDB_STANDALONE__STORAGE__CREDENTIAL: {{ .Values.objectStorage.credentials.serviceAccountKey }}
  {{- end}}
{{- end }}
{{- end }}
{{- end }}
