{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greptimedb-standalone.fullname" . }}-users-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.auth.fileName }}: |
    {{- range .Values.auth.users }}
    {{ printf "%s=%s" .username .password }}
    {{- end }}
{{- end }}
