apiVersion: v2
name: greptimedb-cluster
description: A Helm chart for deploying GreptimeDB cluster in Kubernetes.
type: application
version: 0.2.33
appVersion: 0.9.5
home: https://github.com/GreptimeTeam/greptimedb
sources:
  - https://github.com/GreptimeTeam/greptimedb
keywords:
  - database
  - greptimedb
maintainers:
  - name: daviderli614
    email: liyang@greptime.com
    url: https://github.com/daviderli614
  - name: zyy17
    email: zyy@greptime.com
    url: https://github.com/zyy17

dependencies:
  - name: grafana
    version: "8.5.8"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
