apiVersion: v2
name: greptimedb-cluster
description: A Helm chart for deploying GreptimeDB cluster in Kubernetes.
type: application
version: 0.2.5
appVersion: 0.9.1
home: https://github.com/GreptimeTeam/greptimedb
sources:
  - https://github.com/GreptimeTeam/greptimedb
keywords:
  - database
  - greptimedb
maintainers:
  - name: daviderli614
    email: liyang@greptime.com
    url: https://github.com/daviderli614
  - name: zyy17
    email: zyy@greptime.com
    url: https://github.com/zyy17
