apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  base:
    main:
      image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
      {{- if .Values.base.podTemplate.main.resources }}
      resources: {{- toYaml .Values.base.podTemplate.main.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.base.podTemplate.main.command }}
      command: {{ .Values.base.podTemplate.main.command | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.base.podTemplate.main.args }}
      args: {{ .Values.base.podTemplate.main.args | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.base.podTemplate.main.env }}
      env: {{- toYaml .Values.base.podTemplate.main.env | nindent 8 }}
      {{- end }}
    {{- if .Values.base.podTemplate.annotations }}
    annotations: {{ .Values.base.podTemplate.annotations | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.base.podTemplate.labels }}
    labels: {{ .Values.base.podTemplate.labels | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.base.podTemplate.serviceAccountName }}
    serviceAccountName: {{ .Values.base.podTemplate.serviceAccountName }}
    {{- end }}
    {{- if .Values.base.podTemplate.tolerations }}
    tolerations: {{ .Values.base.podTemplate.tolerations | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.base.podTemplate.affinity }}
    affinity: {{ .Values.base.podTemplate.affinity | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.base.podTemplate.nodeSelector }}
    nodeSelector: {{ .Values.base.podTemplate.nodeSelector | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.image.pullSecrets }}
    imagePullSecrets:
    {{- range .Values.image.pullSecrets }}
      - name: {{ . }}
    {{- end }}
    {{- end }}
  frontend:
    replicas: {{ .Values.frontend.replicas }}
    {{- if .Values.frontend.config }}
    config: |-
      {{ .Values.frontend.config | nindent 6 }}
    {{- end }}
    {{- if .Values.frontend.tls }}
    tls:
      secretName: {{ .Values.frontend.tls.secretName }}
    {{- end }}
    {{- if .Values.frontend.service }}
    service: {{- toYaml .Values.frontend.service | nindent 6 }}
    {{- end }}
    template:
      main:
        {{- if .Values.frontend.podTemplate.main.image }}
        image: {{ .Values.frontend.podTemplate.main.image }}
        {{- end }}
        {{- if .Values.frontend.podTemplate.main.command }}
        command: {{ .Values.frontend.podTemplate.main.command | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.frontend.podTemplate.main.args }}
        args: {{ .Values.frontend.podTemplate.main.args | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.frontend.podTemplate.main.env }}
        env: {{- toYaml .Values.frontend.podTemplate.main.env | nindent 8 }}
        {{- end }}
        {{- if .Values.frontend.podTemplate.main.volumeMounts }}
        volumeMounts: {{- toYaml .Values.frontend.podTemplate.main.volumeMounts | nindent 8 }}
        {{- end }}
        resources:
          requests: {{ .Values.frontend.podTemplate.main.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.frontend.podTemplate.main.resources.limits | toYaml | nindent 12 }}
      {{- if .Values.frontend.podTemplate.annotations }}
      annotations: {{ .Values.frontend.podTemplate.annotations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podTemplate.labels }}
      labels: {{ .Values.frontend.podTemplate.labels | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podTemplate.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}-frontend
      {{- end }}
      {{- if .Values.frontend.podTemplate.tolerations }}
      tolerations: {{ .Values.frontend.podTemplate.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podTemplate.affinity }}
      affinity: {{ .Values.frontend.podTemplate.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podTemplate.nodeSelector }}
      nodeSelector: {{ .Values.frontend.podTemplate.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podTemplate.volumes}}
      volumes: {{ .Values.frontend.podTemplate.volumes | toYaml | nindent 8 }}
      {{- end }}
  meta:
    replicas: {{ .Values.meta.replicas }}
    {{- if .Values.meta.config }}
    config: |-
      {{ .Values.meta.config | nindent 6 }}
    {{- end }}
    {{- if .Values.meta.etcdEndpoints }}
    etcdEndpoints:
      - {{ .Values.meta.etcdEndpoints }}
    {{- end }}
    {{- if .Values.meta.storeKeyPrefix }}
    storeKeyPrefix: {{ .Values.meta.storeKeyPrefix }}
    {{- end }}
    template:
      main:
        {{- if .Values.meta.podTemplate.main.image }}
        image: {{ .Values.meta.podTemplate.main.image }}
        {{- end }}
        {{- if .Values.meta.podTemplate.main.command }}
        command: {{ .Values.meta.podTemplate.main.command | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.meta.podTemplate.main.args }}
        args: {{ .Values.meta.podTemplate.main.args | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.meta.podTemplate.main.env }}
        env: {{- toYaml .Values.meta.podTemplate.main.env | nindent 8 }}
        {{- end }}
        {{- if .Values.meta.podTemplate.main.volumeMounts }}
        volumeMounts: {{- toYaml .Values.meta.podTemplate.main.volumeMounts | nindent 8 }}
        {{- end }}
        resources:
          requests: {{ .Values.meta.podTemplate.main.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.meta.podTemplate.main.resources.limits | toYaml | nindent 12 }}
      {{- if .Values.meta.podTemplate.annotations }}
      annotations: {{ .Values.meta.podTemplate.annotations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podTemplate.labels }}
      labels: {{ .Values.meta.podTemplate.labels | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podTemplate.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}-meta
      {{- end }}
      {{- if .Values.meta.podTemplate.tolerations }}
      tolerations: {{ .Values.meta.podTemplate.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podTemplate.affinity }}
      affinity: {{ .Values.meta.podTemplate.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podTemplate.nodeSelector }}
      nodeSelector: {{ .Values.meta.podTemplate.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podTemplate.volumes}}
      volumes: {{ .Values.meta.podTemplate.volumes | toYaml | nindent 8 }}
      {{- end }}
  datanode:
    replicas: {{ .Values.datanode.replicas }}
    {{- if .Values.datanode.config }}
    config: |-
      {{ .Values.datanode.config | nindent 6 }}
    {{- end }}
    template:
      main:
        {{- if .Values.datanode.podTemplate.main.image }}
        image: {{ .Values.datanode.podTemplate.main.image }}
        {{- end }}
        {{- if .Values.datanode.podTemplate.main.command }}
        command: {{ .Values.datanode.podTemplate.main.command | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.datanode.podTemplate.main.args }}
        args: {{ .Values.datanode.podTemplate.main.args | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.datanode.podTemplate.main.env }}
        env: {{- toYaml .Values.datanode.podTemplate.main.env | nindent 8 }}
        {{- end }}
        {{- if .Values.datanode.podTemplate.main.volumeMounts }}
        volumeMounts: {{- toYaml .Values.datanode.podTemplate.main.volumeMounts | nindent 8 }}
        {{- end }}
        resources:
          requests: {{ .Values.datanode.podTemplate.main.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.datanode.podTemplate.main.resources.limits | toYaml | nindent 12 }}
      {{- if .Values.datanode.podTemplate.annotations }}
      annotations: {{ .Values.datanode.podTemplate.annotations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.datanode.podTemplate.labels }}
      labels: {{ .Values.datanode.podTemplate.labels | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.datanode.podTemplate.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}-datanode
      {{- end }}
      {{- if .Values.datanode.podTemplate.tolerations }}
      tolerations: {{ .Values.datanode.podTemplate.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.datanode.podTemplate.affinity }}
      affinity: {{ .Values.datanode.podTemplate.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.datanode.podTemplate.nodeSelector }}
      nodeSelector: {{ .Values.datanode.podTemplate.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.datanode.podTemplate.volumes}}
      volumes: {{ .Values.datanode.podTemplate.volumes | toYaml | nindent 8 }}
      {{- end }}
    storage:
      storageClassName: {{ .Values.datanode.storage.storageClassName }}
      storageSize: {{ .Values.datanode.storage.storageSize }}
      storageRetainPolicy: {{ .Values.datanode.storage.storageRetainPolicy }}
      dataHome: {{ .Values.datanode.storage.dataHome }}
      walDir: {{ .Values.datanode.storage.walDir }}
  {{- if (and .Values.prometheusMonitor (eq .Values.prometheusMonitor.enabled true ))}}
  prometheusMonitor: {{- toYaml .Values.prometheusMonitor | nindent 4 }}
  {{- end }}
  httpServicePort: {{ .Values.httpServicePort }}
  grpcServicePort: {{ .Values.grpcServicePort }}
  mysqlServicePort: {{ .Values.mysqlServicePort }}
  postgresServicePort: {{ .Values.postgresServicePort }}
  openTSDBServicePort: {{ .Values.openTSDBServicePort }}
  initializer:
    image: '{{ .Values.initializer.registry }}/{{ .Values.initializer.repository }}:{{ .Values.initializer.tag }}'
  objectStorage:
    {{- if .Values.objectStorage.s3 }}
    s3: {{- toYaml .Values.objectStorage.s3 | nindent 6 }}
      {{- if .Values.objectStorage }}
      {{- if .Values.objectStorage.credentials }}
      secretName: {{ default "storage-credentials" .Values.objectStorage.credentials.secretName }}
      {{- end }}
      {{- end }}
    {{- else if .Values.objectStorage.oss }}
    oss: {{- toYaml .Values.objectStorage.oss | nindent 6 }}
      {{- if .Values.objectStorage }}
      {{- if .Values.objectStorage.credentials }}
      secretName: {{ default "storage-credentials" .Values.objectStorage.credentials.secretName }}
      {{- end }}
      {{- end }}
    {{- else }}
    {}
    {{- end }}
