apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  base:
    main:
      image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
      {{- if .Values.resources }}
      resources: {{- toYaml .Values.resources | nindent 8 }}
      {{- end }}
    {{- if .Values.image.pullSecrets }}
    imagePullSecrets:
    {{- range .Values.image.pullSecrets }}
      - name: {{ . }}
    {{- end }}
    {{- end }}
    {{- if .Values.serviceAccount.create }}
    serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
  frontend:
    replicas: {{ .Values.frontend.replicas }}
    {{- if .Values.frontend.config }}
    config: |-
      {{ .Values.frontend.config | nindent 6 }}
    {{- end }}
    {{- if .Values.frontend.tls }}
    tls:
      secretName: {{ .Values.frontend.tls.secretName }}
    {{- end }}
    {{- if .Values.frontend.service }}
    service: {{- toYaml .Values.frontend.service | nindent 6 }}
    {{- end }}
    {{- if .Values.frontend.podTemplate }}
    template: {{- toYaml .Values.frontend.podTemplate | nindent 6 }}
    {{- end }}
  meta:
    replicas: {{ .Values.meta.replicas }}
    {{- if .Values.meta.config }}
    config: |-
      {{ .Values.meta.config | nindent 6 }}
    {{- end }}
    {{- if .Values.meta.etcdEndpoints }}
    etcdEndpoints:
      - {{ .Values.meta.etcdEndpoints }}
    {{- end }}
    {{- if .Values.meta.podTemplate }}
    template: {{- toYaml .Values.meta.podTemplate | nindent 6 }}
    {{- end }}
  datanode:
    replicas: {{ .Values.datanode.replicas }}
    {{- if .Values.datanode.config }}
    config: |-
      {{ .Values.datanode.config | nindent 6 }}
    {{- end }}
    {{- if .Values.datanode.podTemplate }}
    template: {{- toYaml .Values.datanode.podTemplate | nindent 6 }}
    {{- end }}
    storage:
      storageClassName: {{ .Values.datanode.storage.storageClassName }}
      storageSize: {{ .Values.datanode.storage.storageSize }}
      storageRetainPolicy: {{ .Values.datanode.storage.storageRetainPolicy }}
      {{- if .Values.datanode.storage.walDir }}
      walDir: {{ .Values.datanode.storage.walDir }}
      {{- end }}
  {{- if (and .Values.prometheusMonitor (eq .Values.prometheusMonitor.enabled true ))}}
  prometheusMonitor: {{- toYaml .Values.prometheusMonitor | nindent 4 }}
  {{- end }}
  httpServicePort: {{ .Values.httpServicePort }}
  grpcServicePort: {{ .Values.grpcServicePort }}
  mysqlServicePort: {{ .Values.mysqlServicePort }}
  postgresServicePort: {{ .Values.postgresServicePort }}
  openTSDBServicePort: {{ .Values.openTSDBServicePort }}
  initializer:
    image: '{{ .Values.initializer.registry }}/{{ .Values.initializer.repository }}:{{ .Values.initializer.tag }}'
  storage:
    {{- if .Values.storage.s3 }}
    s3:
      bucket: {{ .Values.storage.s3.bucket }}
      region: {{ .Values.storage.s3.region }}
      root: {{ .Values.storage.s3.root }}
      secretName: {{ .Values.storage.credentials.secretName }}
      endpoint: {{ .Values.storage.s3.endpoint }}
    {{- else if .Values.storage.local }}
    local:
      directory: {{ .Values.storage.local.directory }}
    {{- else if .Values.storage.oss }}
    oss:
      bucket: {{ .Values.storage.oss.bucket }}
      region: {{ .Values.storage.oss.region }}
      root: {{ .Values.storage.oss.root }}
      secretName: {{ .Values.storage.credentials.secretName }}
      endpoint: {{ .Values.storage.oss.endpoint }}
    {{- else }}
    {}
    {{- end }}
