{{- if .Values.customImageRegistry.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.customImageRegistry.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-cluster.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "dockerConfigJSON" . | b64enc }}
{{- end }}
