{{- if .Values.datanode.podTemplate.serviceaccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-datanode
  namespace: {{ .Release.Namespace }}
  {{- with .Values.datanode.podTemplate.serviceaccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
