{{- if .Values.debug }}
{{- if .Values.debug.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-debug
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-debug
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-debug
    spec:
      containers:
        - image: {{ printf "%s/%s:%s" .Values.debug.image.registry .Values.debug.image.repository .Values.debug.image.tag }}
          name: {{ .Release.Name }}-debug
          {{- if .Values.debug.resources }}
          resources: {{ toYaml .Values.debug.resources | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
