{{- if and .Values.license.enabled (not .Values.license.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-license" .Release.Name) .Values.license.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.license.mountFileName }}: |-
    {{- .Values.license.data | nindent 4 }}
{{- end }}
