{{- if .Values.meta.backendStorage.mysql }}
{{- if .Values.meta.backendStorage.mysql.credentials }}
{{- if not .Values.meta.backendStorage.mysql.credentials.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "meta-mysql-credentials" .Values.meta.backendStorage.mysql.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.meta.backendStorage.mysql.credentials.username }}
  password: {{ .Values.meta.backendStorage.mysql.credentials.password }}
{{- end }}
{{- end }}
{{- end }}
