{{- if .Values.objectStorage }}
{{- if .Values.objectStorage.credentials }}
{{- if not .Values.objectStorage.credentials.existingSecretName }}
apiVersion: v1
metadata:
  name: {{ default "storage-credentials" .Values.objectStorage.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-cluster.labels" . | nindent 4 }}
kind: Secret
type: Opaque
{{- if .Values.objectStorage.credentials.serviceAccountKey }}
data:
  service-account-key: {{ .Values.objectStorage.credentials.serviceAccountKey }}
{{- else }}
stringData:
  {{- if .Values.objectStorage.credentials.accessKeyId }}
  access-key-id: {{ .Values.objectStorage.credentials.accessKeyId }}
  {{- end }}
  {{- if .Values.objectStorage.credentials.secretAccessKey }}
  secret-access-key: {{ .Values.objectStorage.credentials.secretAccessKey }}
  {{- end }}
  {{- if .Values.objectStorage.credentials.accountName }}
  account-name: {{ .Values.objectStorage.credentials.accountName }}
  {{- end }}
  {{- if .Values.objectStorage.credentials.accountKey }}
  account-key: {{ .Values.objectStorage.credentials.accountKey }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
