{{- if .Values.objectStorage }}
{{- if .Values.objectStorage.credentials }}
apiVersion: v1
metadata:
  {{- if .Values.objectStorage.credentials.secretName }}
  name: {{ .Values.objectStorage.credentials.secretName }}
  {{- else }}
  name: greptimedb-credentials
  {{- end }}
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
stringData:
  access-key-id: {{ .Values.objectStorage.credentials.accessKeyId }}
  secret-access-key: {{ .Values.objectStorage.credentials.secretAccessKey }}
{{- end }}
{{- end }}
