{{- if .Values.objectStorage }}
{{- if .Values.objectStorage.credentials }}
{{- if .Values.objectStorage.credentials.existingSecretName }}
{{- else }}
apiVersion: v1
metadata:
  name: {{ default "storage-credentials" .Values.objectStorage.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
stringData:
  access-key-id: {{ .Values.objectStorage.credentials.accessKeyId }}
  secret-access-key: {{ .Values.objectStorage.credentials.secretAccessKey }}
{{- end }}
{{- end }}
{{- end }}
