{{- if .Values.objectStorage }}
{{- if .Values.objectStorage.credentials }}
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
stringData:
  access-key-id: {{ .Values.objectStorage.credentials.accessKeyId }}
  secret-access-key: {{ .Values.objectStorage.credentials.secretAccessKey }}
{{- end }}
{{- end }}
