{{- if .Values.objectStorage }}
{{- if .Values.objectStorage.credentials }}
{{- if not .Values.objectStorage.credentials.existingSecretName }}
apiVersion: v1
metadata:
  name: {{ default "storage-credentials" .Values.objectStorage.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
{{- if .Values.objectStorage.credentials.serviceAccountKey }}
data:
  service-account-key: {{ .Values.objectStorage.credentials.serviceAccountKey }}
{{- else }}
stringData:
  access-key-id: {{ .Values.objectStorage.credentials.accessKeyId }}
  secret-access-key: {{ .Values.objectStorage.credentials.secretAccessKey }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
