{{- if and .Values.flownode.enabled .Values.flownode.podTemplate.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-flownode
  namespace: {{ .Release.Namespace }}
  {{- with .Values.flownode.podTemplate.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
