{{- if .Values.datanode.podTemplate.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-datanode
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-cluster.labels" . | nindent 4 }}
  {{- with .Values.datanode.podTemplate.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
