{{- if .Values.frontend.tls.certificates }}
{{- if .Values.frontend.tls.certificates.secretCreation }}
{{- if and (eq .Values.frontend.tls.certificates.secretCreation.enabled true) (eq .Values.frontend.tls.certificates.secretCreation.enableEncryption false) }}
apiVersion: v1
metadata:
  name: {{ .Values.frontend.tls.certificates.secretName }}
  namespace: {{ .Release.Namespace }}
kind: Secret
type: kubernetes.io/tls
data:
  {{- toYaml .Values.frontend.tls.certificates.secretCreation.data | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
