{{- if .Values.infraTesting.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
stringData:
  access_key_id: {{ .Values.infraTesting.accessKeyID | quote }}
  secret_access_key: {{ .Values.infraTesting.secretAccessKey | quote }}
{{- end }}
