{{- if and .Values.preCheck.enabled .Values.preCheck.case.disk .Values.preCheck.case.disk.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pre-check-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-weight": "-2"
spec:
  storageClassName: {{ .Values.preCheck.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.preCheck.size }}
{{- end }}
