{
 "title": "GreptimeDB Cluster Metrics",
 "description": "The Grafana dashboard of GreptimeDB cluster.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(greptime_app_version,cluster)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(greptime_app_version{cluster=\"$cluster\", app=~\"greptime-datanode|greptime-metasrv|greptime-flownode|greptime-frontend\"},app)"
    }
   },
   {
    "name": "pods",
    "query": {
     "query": "label_values(greptime_app_version{cluster=\"$cluster\", app=~\"$role\"},pod)"
    }
   },
   {
    "name": "datanode",
    "query": {
     "query": "label_values(greptime_app_version{cluster=\"$cluster\", app=\"greptime-datanode\"},pod)"
    }
   },
   {
    "name": "frontend",
    "query": {
     "query": "label_values(greptime_app_version{cluster=\"$cluster\", app=\"greptime-frontend\"},pod)"
    }
   },
   {
    "name": "metasrv",
    "query": {
     "query": "label_values(greptime_app_version{cluster=\"$cluster\", app=\"greptime-metasrv\"},pod)"
    }
   },
   {
    "name": "flownode",
    "query": {
     "query": "label_values(greptime_app_version{cluster=\"$cluster\", app=\"greptime-flownode\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(greptime_app_version[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus-write-total-qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum (rate(greptime_servers_http_prometheus_write_elapsed_bucket{pod=~\"$frontend\"}[$__rate_interval]))",
     "legendFormat": "prometheus-write"
    }
   ]
  },
  { "title": "Frontend-Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "frontend-memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sys_jemalloc_allocated{pod=~\"$frontend\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(sys_jemalloc_resident{pod=~\"$frontend\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{pod=~\"$frontend\"})",
     "legendFormat": "virtual-memory"
    }
   ]
  },
  { "title": "Frontend-APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "http-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, path, method, code) (rate(greptime_servers_http_requests_elapsed_count{pod=~\"$frontend\",path!~\"/health|/metrics\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-qps"
    }
   ]
  },
  {
   "title": "http-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, path, method, code) (rate(greptime_servers_http_requests_elapsed_bucket{pod=~\"$frontend\",path!~\"/health|/metrics\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-p99"
    }
   ]
  },
  {
   "title": "grpc-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, path, code) (rate(greptime_servers_grpc_requests_elapsed_count{pod=~\"$frontend\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{path}}]-[{{code}}]-qps"
    }
   ]
  },
  {
   "title": "grpc-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, path, code) (rate(greptime_servers_grpc_requests_elapsed_bucket{pod=~\"$frontend\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-p99"
    }
   ]
  },
  {
   "title": "mysql-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate(greptime_servers_mysql_query_elapsed_count{pod=~\"$frontend\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-qps"
    }
   ]
  },
  {
   "title": "mysql-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod) (rate(greptime_servers_mysql_query_elapsed_bucket{pod=~\"$frontend\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-p99"
    }
   ]
  },
  {
   "title": "postgres-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(greptime_servers_postgres_query_elapsed_count{pod=~\"$frontend\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-qps"
    }
   ]
  },
  {
   "title": "postgres-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod) (rate(greptime_servers_postgres_query_elapsed_count{pod=~\"$frontend\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-p99"
    }
   ]
  },
  { "title": "Frontend <-> Datanode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "ingest-rows-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate(greptime_table_operator_ingest_rows{pod=~\"$frontend\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-rps"
    }
   ]
  },
  {
   "title": "region-call-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, request_type) (rate(greptime_grpc_region_request_count{pod=~\"$frontend\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{request_type}}]-qps"
    }
   ]
  },
  {
   "title": "region-call-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, request_type) (rate(greptime_grpc_region_request_bucket{pod=~\"$frontend\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{request_type}}]-p99"
    }
   ]
  },
  { "title": "Datanode-Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "datanode-memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sys_jemalloc_allocated{pod=~\"$datanode\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(sys_jemalloc_resident{pod=~\"$datanode\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{pod=~\"$datanode\"})",
     "legendFormat": "virtual-memory"
    }
   ]
  },
  { "title": "Datanode-Mito", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "request-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, type) (rate(greptime_mito_handle_request_elapsed_count{pod=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{type}}]-qps"
    }
   ]
  },
  {
   "title": "request-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, type) (rate(greptime_mito_handle_request_elapsed_bucket{pod=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{type}}]-p99"
    }
   ]
  },
  {
   "title": "write-buffer-bytes-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "greptime_mito_write_buffer_bytes{pod=~\"$datanode\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "write-stall-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (greptime_mito_write_stall_total{pod=~\"$datanode\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "flush-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, reason) (rate(greptime_mito_flush_requests_total{pod=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{reason}}]-success"
    }
   ]
  },
  {
   "title": "cached-bytes-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "greptime_mito_cache_bytes{pod=~\"$datanode\"}",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "read-stage-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(greptime_mito_read_stage_elapsed_count{pod=~\"$datanode\", stage=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-p99"
    }
   ]
  },
  {
   "title": "read-stage-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, stage) (rate(greptime_mito_read_stage_elapsed_bucket{pod=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}-{{stage}}-p99"
    }
   ]
  },
  {
   "title": "compaction-ops-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(greptime_mito_compaction_total_elapsed_count{pod=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "compaction-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le) (rate(greptime_mito_compaction_total_elapsed_bucket{pod=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-compaction-p99"
    }
   ]
  },
  {
   "title": "write-stage-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, stage) (rate(greptime_mito_write_stage_elapsed_bucket{pod=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}-{{stage}}-p99"
    }
   ]
  },
  {
   "title": "compaction-stage-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, stage) (rate(greptime_mito_compaction_stage_elapsed_bucket{pod=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}-{{stage}}-p99"
    }
   ]
  },
  { "title": "Datanode-ObjectStorage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "total-requests-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, scheme, operation) (rate(opendal_requests_total{pod=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-[{{operation}}]-qps"
    }
   ]
  },
  {
   "title": "read-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, scheme) (rate(opendal_requests_duration_seconds_count{pod=~\"$datanode\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-qps"
    }
   ]
  },
  {
   "title": "read-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{pod=~\"$datanode\",operation=\"read\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-{{scheme}}-p99"
    }
   ]
  },
  {
   "title": "write-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, scheme) (rate(opendal_requests_duration_seconds_count{pod=~\"$datanode\", operation=\"write\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-qps"
    }
   ]
  },
  {
   "title": "write-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{pod=~\"$datanode\", operation=\"write\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-p99"
    }
   ]
  },
  {
   "title": "list-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, scheme) (rate(opendal_requests_duration_seconds_count{pod=~\"$datanode\", operation=\"list\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-qps"
    }
   ]
  },
  {
   "title": "list-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{pod=~\"$datanode\", operation=\"list\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-p99"
    }
   ]
  },
  {
   "title": "other-requests-qps-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod, scheme, operation) (rate(opendal_requests_duration_seconds_count{pod=~\"$datanode\",operation!~\"read|write|list|stat\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-[{{operation}}]qps"
    }
   ]
  },
  {
   "title": "other-requests-p99-by-pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le, scheme, operation) (rate(opendal_requests_duration_seconds_bucket{pod=~\"$datanode\", operation!~\"read|write|list\"}[$__rate_interval])))",
     "legendFormat": "[{{pod}}]-[{{scheme}}]-[{{operation}}]-p99"
    }
   ]
  },
  { "title": "Metasrv", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "metasrv-memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sys_jemalloc_allocated{pod=~\"$metasrv\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(sys_jemalloc_resident{pod=~\"$metasrv\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{pod=~\"$metasrv\"})",
     "legendFormat": "virtual-memory"
    }
   ]
  }
 ]
}