name: "Build Debug Pod Image"

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          # The latest version will lead to segmentation fault.
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to AliCloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.OCI_REGISTRY_URL }}
          username: ${{ secrets.ALICLOUD_USERNAME }}
          password: ${{ secrets.ALICLOUD_PASSWORD }}

      - name: Configure build image tag # The image tag will be like '20230116-6441c463'
        shell: bash
        run: |
          buildTime=`date "+%Y%m%d"`
          commitShortSHA=`git log -1 --pretty=format:"%h"`
          IMAGE_TAG="$buildTime-$commitShortSHA"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/debug-pod/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REGISTRY_URL }}/greptime/greptime-tool:${{ env.IMAGE_TAG }}
            ${{ vars.OCI_REGISTRY_URL }}/greptime/greptime-tool:${{ env.IMAGE_TAG }}
