name: CI

on: [push, pull_request]

jobs:
  chart-test:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'GreptimeTeam/helm-charts' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check docs
        run: |
          make check-docs

      - name: Check crds
        run: |
          make check-crds    

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Testing add greptime helm repo
        run: |
          helm repo add greptime https://greptimeteam.github.io/helm-charts/
          helm repo add grafana https://grafana.github.io/helm-charts/
          helm repo add jaeger-all-in-one https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts/
          helm search repo greptime

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs charts --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi 

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0
        with:
          wait: 120s
          version: v0.32.0
          kubectl_version: v1.32.0

      - name: Run e2e
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          make e2e
