name: E2E

on:
  workflow_dispatch:
    inputs:
      chart:
        type: choice
        description: Chart Name
        required: true
        options:
          - greptimedb-cluster
          - greptimedb-standalone

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          wait: 120s

      - name: Deploy greptimedb-cluster
        if: ${{ github.event.inputs.chart == 'greptimedb-cluster' }}
        shell: bash
        run: |
          make e2e-greptimedb-cluster

      - name: Deploy greptimedb-standalone
        if: ${{ github.event.inputs.chart == 'greptimedb-standalone' }}
        shell: bash
        run: |
          make e2e-greptimedb-standalone
