name: Release
on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package Charts
        run: |
          helm package ./charts/greptimedb-operator
          helm package ./charts/greptimedb

      - name: Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            greptimedb-${{ env.RELEASE_VERSION }}.tgz
            greptimedb-operator-${{ env.RELEASE_VERSION }}.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
